# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: es6-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

defaults:
  stage: dev
  region: eu-west-1


functions:
  uppercase:
    handler: lib/handler.uppercase
    memory: 128
    timeout: 3
    events:
      - http:
          path: uppercase
          method: GET
          cors: true
  nodefetch:
    handler: lib/handler.nodefetch
    memory: 128
    timeout: 3
    events:
      - http:
          path: nodefetch
          method: GET
          cors: true


package:
  include:
    - lib
    - node_modules
  exclude:
    - .gitignore
    - .synk
    - .travis.yml
    - deploy.sh
    - package.json
    - README.md


plugins:
  - serverless-scriptable-plugin
  
custom:
  scriptHooks:
    before:deploy:createDeploymentArtifacts: build/package.js
    
#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
